import fs from "node:fs";
import path from "node:path";

import { findPackageRoot } from "server/utils/assets.js";

import { WrapperLaunchConfig } from "./index.js";

/// In development, use the jar generated by the local build (if available)
const PACKAGE_ROOT = findPackageRoot();
const WRAPPER_DEVELOPMENT_FOLDER = path.join(PACKAGE_ROOT, "../rumble-lsp-wrapper");
const WRAPPER_JAR_DEVELOPMENT_FOLDER = path.join(WRAPPER_DEVELOPMENT_FOLDER, "target");
const RUMBLE_JAR_DEVELOPMENT_FOLDER = path.join(WRAPPER_DEVELOPMENT_FOLDER, "rumbledb", "target");

const WRAPPER_RUNTIME_CLASSPATH_FILE = "runtime-classpath.txt";
const WRAPPER_MAIN_CLASS = "org.jsoniq.lsp.wrapper.Main";

export function resolveDevLaunchConfig(): WrapperLaunchConfig | undefined {
    const localJarPath = pickLatestJarFromDirectory(WRAPPER_JAR_DEVELOPMENT_FOLDER);
    const classpathPath = path.join(WRAPPER_JAR_DEVELOPMENT_FOLDER, WRAPPER_RUNTIME_CLASSPATH_FILE);
    if (localJarPath === undefined || !fs.existsSync(classpathPath)) {
        return undefined;
    }

    const rumbleJarPath = pickLatestJarFromDirectory(RUMBLE_JAR_DEVELOPMENT_FOLDER);
    const runtimeClasspath = fs.readFileSync(classpathPath, "utf8").trim();
    const classpathEntries = [
        localJarPath,
        rumbleJarPath,
        ...runtimeClasspath.split(path.delimiter),
    ].filter((entry): entry is string => entry !== undefined);
    const classpath = [...new Set(classpathEntries)].join(path.delimiter);

    return {
        args: ["-cp", classpath, WRAPPER_MAIN_CLASS, "--daemon"],
    };
}

function pickLatestJarFromDirectory(directory: string): string | undefined {
    if (!fs.existsSync(directory)) {
        return undefined;
    }

    const files = fs.readdirSync(directory);
    const wrapperJars = files
        .filter((file) => file.endsWith(".jar"))
        .map((file) => path.join(directory, file))
        .sort((a, b) => fs.statSync(b).mtime.getTime() - fs.statSync(a).mtime.getTime());

    return wrapperJars[0];
}
